CREATE DATABASE NewsAppDb;
GO

CREATE LOGIN news_app WITH
    PASSWORD = '<SET_LOCALLY>',
    CHECK_POLICY = ON,
    DEFAULT_DATABASE = NewsAppDb;
GO

USE NewsAppDb;
GO
CREATE USER news_app FOR LOGIN news_app;
GO

ALTER ROLE db_owner ADD MEMBER news_app;
GO